/*
 * Copyright (c) 2025-2026 Tiger Data, Inc.
 * Licensed under the PostgreSQL License. See LICENSE for details.
 *
 * fieldnorm.h - Document length quantization for BM25 scoring
 *
 * Uses Lucene's SmallFloat encoding scheme which maps document lengths
 * to a single byte (256 buckets). This reduces storage while maintaining
 * good BM25 ranking quality because:
 * - BM25 uses the ratio dl/avgdl, not absolute length
 * - Small errors become smaller in the ratio
 * - The b parameter (0.75) further dampens length's influence
 *
 * Key properties:
 * - Lengths 0-39 stored exactly (covers most short documents)
 * - Larger lengths use 4-bit mantissa (~6% relative error max)
 * - 256 buckets cover lengths from 0 to 2+ billion
 */
#pragma once

#include "postgres.h"

/*
 * Precomputed decode table (Lucene SmallFloat.byte4ToInt)
 *
 * Generated by: for i in 0..255: decode_table[i] = byte4ToInt(i)
 * Values 0-39 map exactly, larger values use exponential encoding.
 */
static const uint32 FIELDNORM_DECODE_TABLE[256] = {
		/* 0-15: exact values */
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		/* 16-31: exact values */
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		/* 32-39: exact values */
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		/* 40-47: step 2 */
		40,
		42,
		44,
		46,
		48,
		50,
		52,
		54,
		/* 48-55: step 4 */
		56,
		60,
		64,
		68,
		72,
		76,
		80,
		84,
		/* 56-63: step 8 */
		88,
		96,
		104,
		112,
		120,
		128,
		136,
		144,
		/* 64-71: step 16 */
		152,
		168,
		184,
		200,
		216,
		232,
		248,
		264,
		/* 72-79: step 32 */
		280,
		312,
		344,
		376,
		408,
		440,
		472,
		504,
		/* 80-87: step 64 */
		536,
		600,
		664,
		728,
		792,
		856,
		920,
		984,
		/* 88-95: step 128 */
		1048,
		1176,
		1304,
		1432,
		1560,
		1688,
		1816,
		1944,
		/* 96-103: step 256 */
		2072,
		2328,
		2584,
		2840,
		3096,
		3352,
		3608,
		3864,
		/* 104-111: step 512 */
		4120,
		4632,
		5144,
		5656,
		6168,
		6680,
		7192,
		7704,
		/* 112-119: step 1024 */
		8216,
		9240,
		10264,
		11288,
		12312,
		13336,
		14360,
		15384,
		/* 120-127: step 2048 */
		16408,
		18456,
		20504,
		22552,
		24600,
		26648,
		28696,
		30744,
		/* 128-135: step 4096 */
		32792,
		36888,
		40984,
		45080,
		49176,
		53272,
		57368,
		61464,
		/* 136-143: step 8192 */
		65560,
		73752,
		81944,
		90136,
		98328,
		106520,
		114712,
		122904,
		/* 144-151: step 16384 */
		131096,
		147480,
		163864,
		180248,
		196632,
		213016,
		229400,
		245784,
		/* 152-159: step 32768 */
		262168,
		294936,
		327704,
		360472,
		393240,
		426008,
		458776,
		491544,
		/* 160-167: step 65536 */
		524312,
		589848,
		655384,
		720920,
		786456,
		851992,
		917528,
		983064,
		/* 168-175: step 131072 */
		1048600,
		1179672,
		1310744,
		1441816,
		1572888,
		1703960,
		1835032,
		1966104,
		/* 176-183: step 262144 */
		2097176,
		2359320,
		2621464,
		2883608,
		3145752,
		3407896,
		3670040,
		3932184,
		/* 184-191: step 524288 */
		4194328,
		4718616,
		5242904,
		5767192,
		6291480,
		6815768,
		7340056,
		7864344,
		/* 192-199: step 1048576 */
		8388632,
		9437208,
		10485784,
		11534360,
		12582936,
		13631512,
		14680088,
		15728664,
		/* 200-207: step 2097152 */
		16777240,
		18874392,
		20971544,
		23068696,
		25165848,
		27263000,
		29360152,
		31457304,
		/* 208-215: step 4194304 */
		33554456,
		37748760,
		41943064,
		46137368,
		50331672,
		54525976,
		58720280,
		62914584,
		/* 216-223: step 8388608 */
		67108888,
		75497496,
		83886104,
		92274712,
		100663320,
		109051928,
		117440536,
		125829144,
		/* 224-231: step 16777216 */
		134217752,
		150994968,
		167772184,
		184549400,
		201326616,
		218103832,
		234881048,
		251658264,
		/* 232-239: step 33554432 */
		268435480,
		301989912,
		335544344,
		369098776,
		402653208,
		436207640,
		469762072,
		503316504,
		/* 240-247: step 67108864 */
		536870936,
		603979800,
		671088664,
		738197528,
		805306392,
		872415256,
		939524120,
		1006632984,
		/* 248-255: step 134217728 */
		1073741848,
		1207959576,
		1342177304,
		1476395032,
		1610612760,
		1744830488,
		1879048216,
		2013265944};

/*
 * Encode document length to fieldnorm byte via binary search.
 *
 * Finds the largest index i where FIELDNORM_DECODE_TABLE[i] <= length.
 * This matches Tantivy's fieldnorm_to_id implementation.
 */
static inline uint8
encode_fieldnorm(uint32 length)
{
	int lo = 0;
	int hi = 255;

	while (lo < hi)
	{
		int mid = (lo + hi + 1) / 2;
		if (FIELDNORM_DECODE_TABLE[mid] <= length)
			lo = mid;
		else
			hi = mid - 1;
	}
	return (uint8)lo;
}

/*
 * Decode fieldnorm byte back to approximate document length
 */
static inline uint32
decode_fieldnorm(uint8 norm_id)
{
	return FIELDNORM_DECODE_TABLE[norm_id];
}
